services:
  postgres:
    image: postgres:15
    container_name: tcc_postgres
    environment:
      POSTGRES_USER: tcc
      POSTGRES_PASSWORD: tcc123
      POSTGRES_DB: inadimplencia
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: